### ISSUE TITLE
pbpaste redirection not working

### ISSUE THREAD

**Issue by adbennet** [ColdGrub1384/LibTerm#2]
Neither | nor > works with pbpaste. Maybe it is going to stderr instead of stdout? 
A simple demo:
$ echo 'foo bar' > tmp
$ wc tmp 
       1       2       8 tmp
$ cat tmp | pbcopy
$ pbpaste
foo bar
$ pbpaste | wc
foo bar
       0       0       0
$ pbpaste > tmp
foo bar
$ wc tmp
       0       0       0 tmp
$

**Comment by ColdGrub1384** [comment]
Very strange... pbpaste prints to the stdout but doesn't write to the file. It doesn't write to the stderr since the text is printed in green and not in red. I will try to debug.

**Comment by ColdGrub1384** [comment]
I fixed it

**Comment by adbennet** [comment]
I am still seeing the same behavior in "LibTerm version 3.0.1 (3), Dec 16, 2018 at 11:27 AM". Later I will update to version 4 and retry.

**Comment by ColdGrub1384** [comment]
It seems commands failed to replace. Thank you for reporting!

**Comment by ColdGrub1384** [comment]
I just fixed it.
